import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
import { addDoc, collection, doc, getDoc, getDocs, initializeFirestore, query, serverTimestamp, setDoc, where } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";
import { calculatePhilippineDeductions } from "./statutory.js?v=1";

const firebaseConfig={apiKey:"AIzaSyDFW61pnwLvh6HGKWt10zLYNr860fI8vkg",authDomain:"driva-pwa.firebaseapp.com",databaseURL:"https://driva-pwa-default-rtdb.firebaseio.com",projectId:"driva-pwa",storageBucket:"driva-pwa.firebasestorage.app",messagingSenderId:"299138219722",appId:"1:299138219722:web:623ff6b0a067ea822dfe33"};
const db=initializeFirestore(initializeApp(firebaseConfig),{},"drver-task");
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const $=id=>document.getElementById(id);
const ui={dateFrom:$("dateFrom"),dateTo:$("dateTo"),loadBtn:$("loadBtn"),saveDraftBtn:$("saveDraftBtn"),finalizeBtn:$("finalizeBtn"),markPaidBtn:$("markPaidBtn"),exportBtn:$("exportBtn"),printBtn:$("printBtn"),searchBox:$("searchBox"),message:$("message"),runStatus:$("runStatus"),periodLabel:$("periodLabel"),payrollBody:$("payrollBody"),employeeCount:$("employeeCount"),workdayCount:$("workdayCount"),taskCount:$("taskCount"),grossTotal:$("grossTotal"),employeeForm:$("employeeForm"),employeeFormTitle:$("employeeFormTitle"),employeeId:$("employeeId"),employeeName:$("employeeName"),employeePosition:$("employeePosition"),employeeStartDate:$("employeeStartDate"),employeeRate:$("employeeRate"),employeeActive:$("employeeActive"),saveEmployeeBtn:$("saveEmployeeBtn"),cancelEmployeeBtn:$("cancelEmployeeBtn"),employeeSearch:$("employeeSearch"),employeeBody:$("employeeBody"),historyBody:$("historyBody"),refreshHistoryBtn:$("refreshHistoryBtn")};
ui.attendanceSource=$("attendanceSource");
let employees=new Map(),payrollRows=[],payrollHistory=[],editingEmployeeId="",currentRun=null;

function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}
function todayPH(){return new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Manila"});}
function money(v){return peso.format(Number(v)||0);}
function dateText(v){if(!v)return "—";const d=typeof v.toDate==="function"?v.toDate():new Date(v);return isNaN(d)?"—":d.toLocaleString("en-PH",{timeZone:"Asia/Manila"});}
function message(text,type=""){ui.message.className=`message${type?` ${type}`:""}`;ui.message.textContent=text;}
function taskDriver(task){return String(task.completedBy||task.agentId||task.driverId||"").trim();}
function completed(task){return String(task.status||"").toUpperCase()==="COMPLETED"||String(task.workStatus||"").toUpperCase()==="COMPLETED";}
function runId(){return `${ui.dateFrom.value}_${ui.dateTo.value}`;}

function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("hidden",v.id!==id));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===id));if(id==="employeesView")loadEmployees();if(id==="historyView")loadHistory();}
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>showView(tab.dataset.view)));

async function loadEmployees(){
  ui.employeeBody.innerHTML='<tr><td colspan="7" class="empty">Loading employees...</td></tr>';
  try{
    const snap=await getDocs(collection(db,"payrollEmployees"));employees=new Map();
    snap.forEach(d=>{const data=d.data()||{};const id=String(data.employeeId||d.id).trim();employees.set(id.toUpperCase(),{...data,employeeId:id});});
    renderEmployees();
  }catch(error){console.error(error);ui.employeeBody.innerHTML='<tr><td colspan="7" class="empty">Unable to load employees.</td></tr>';message("Unable to load payroll employees.","error");}
}
function renderEmployees(){
  const term=ui.employeeSearch.value.trim().toLowerCase();const rows=[...employees.values()].filter(e=>`${e.employeeId} ${e.name} ${e.position}`.toLowerCase().includes(term)).sort((a,b)=>a.employeeId.localeCompare(b.employeeId));
  ui.employeeBody.innerHTML=rows.length?rows.map(e=>`<tr><td><strong>${esc(e.employeeId)}</strong></td><td>${esc(e.name)}</td><td>${esc(e.position||"—")}</td><td>${esc(e.startDate||"—")}</td><td class="number">${money(e.dailyRate)}</td><td><span class="status-pill ${e.active===false?"inactive":"active"}">${e.active===false?"Inactive":"Active"}</span></td><td><div class="action-row"><button class="small-btn" data-edit="${esc(e.employeeId)}">Edit</button><button class="small-btn" data-toggle="${esc(e.employeeId)}">${e.active===false?"Activate":"Deactivate"}</button></div></td></tr>`).join(""):'<tr><td colspan="7" class="empty">No employees found.</td></tr>';
}
function resetEmployeeForm(){editingEmployeeId="";ui.employeeForm.reset();ui.employeeActive.checked=true;ui.attendanceSource.value="TASKS";ui.employeeId.readOnly=false;ui.employeeFormTitle.textContent="Add Employee";ui.saveEmployeeBtn.textContent="Save Employee";ui.cancelEmployeeBtn.classList.add("hidden");}
function editEmployee(id){const e=employees.get(id.toUpperCase());if(!e)return;editingEmployeeId=e.employeeId;ui.employeeId.value=e.employeeId;ui.employeeId.readOnly=true;ui.employeeName.value=e.name||"";ui.employeePosition.value=e.position||"";ui.employeeStartDate.value=e.startDate||"";ui.employeeRate.value=Number(e.dailyRate)||0;ui.attendanceSource.value=e.attendanceSource||"TASKS";ui.employeeActive.checked=e.active!==false;ui.employeeFormTitle.textContent="Edit Employee";ui.saveEmployeeBtn.textContent="Save Changes";ui.cancelEmployeeBtn.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
async function saveEmployee(event){
  event.preventDefault();const id=ui.employeeId.value.trim();const rate=Number(ui.employeeRate.value);if(!id||!ui.employeeName.value.trim())return message("Employee ID and name are required.","error");if(id.includes("/"))return message("Employee ID cannot contain a slash.","error");if(!Number.isFinite(rate)||rate<0)return message("Enter a valid daily rate.","error");
  if(!editingEmployeeId&&employees.has(id.toUpperCase()))return message("That Employee ID already exists. Use Edit instead.","error");
  ui.saveEmployeeBtn.disabled=true;try{await setDoc(doc(db,"payrollEmployees",id),{employeeId:id,name:ui.employeeName.value.trim(),position:ui.employeePosition.value.trim(),startDate:ui.employeeStartDate.value,dailyRate:rate,attendanceSource:ui.attendanceSource.value,active:ui.employeeActive.checked,updatedAt:serverTimestamp(),...(!editingEmployeeId?{createdAt:serverTimestamp()}:{})},{merge:true});message(`Employee ${id} saved.`,"success");resetEmployeeForm();await loadEmployees();}catch(error){console.error(error);message(`Employee could not be saved: ${error.message||error}`,"error");}finally{ui.saveEmployeeBtn.disabled=false;}
}
async function toggleEmployee(id){const e=employees.get(id.toUpperCase());if(!e)return;const active=e.active===false;try{await setDoc(doc(db,"payrollEmployees",e.employeeId),{active,updatedAt:serverTimestamp()},{merge:true});message(`${e.employeeId} is now ${active?"active":"inactive"}.`,"success");await loadEmployees();}catch(error){console.error(error);message("Employee status could not be changed.","error");}}

async function loadCompletedTasks(from,to){const q=query(collection(db,"TASK"),where("assignedDate",">=",from),where("assignedDate","<=",to));const snap=await getDocs(q);const tasks=[];snap.forEach(d=>{const t={_key:d.id,...d.data()};if(t.deleted!==true&&completed(t))tasks.push(t);});return tasks;}
async function loadManualData(from,to){const [a,l,s]=await Promise.all([getDocs(query(collection(db,"payrollAttendance"),where("date",">=",from),where("date","<=",to))),getDocs(collection(db,"payrollLeaves")),getDoc(doc(db,"payrollSettings","general"))]);const attendance=[],leaves=[];a.forEach(d=>attendance.push(d.data()));l.forEach(d=>{const x=d.data();if(x.to>=from&&x.from<=to)leaves.push(x);});return{attendance,leaves,paidStatuses:s.exists()?(s.data().paidStatuses||[]):["PRESENT","VACATION_LEAVE","SICK_LEAVE","HOLIDAY"]};}
function eachDate(from,to){const dates=[];let d=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);while(d<=end){const text=d.toISOString().slice(0,10);if(text>=ui.dateFrom.value&&text<=ui.dateTo.value)dates.push(text);d.setUTCDate(d.getUTCDate()+1);}return dates;}
function calculatePayroll(tasks,manual){const grouped=new Map(),ensure=(key,id)=>{if(!grouped.has(key))grouped.set(key,{key,employeeId:id,taskCount:0,dates:new Set()});return grouped.get(key);};tasks.forEach(task=>{const raw=taskDriver(task);if(!raw)return;const key=raw.toUpperCase(),e=employees.get(key);if(e?.attendanceSource==="MANUAL")return;const row=ensure(key,raw);row.taskCount++;const day=String(task.assignedDate||"").slice(0,10);if(day)row.dates.add(day);});manual.attendance.forEach(x=>{const key=String(x.employeeId||"").toUpperCase(),e=employees.get(key);if(e?.attendanceSource==="MANUAL"&&manual.paidStatuses.includes(x.status))ensure(key,e.employeeId).dates.add(x.date);});manual.leaves.forEach(x=>{const key=String(x.employeeId||"").toUpperCase(),e=employees.get(key);if(e?.attendanceSource!=="MANUAL"||x.status!=="APPROVED"||x.paid!==true)return;eachDate(x.from,x.to).forEach(date=>ensure(key,e.employeeId).dates.add(date));});return [...grouped.values()].map(row=>{const e=employees.get(row.key),paidDays=row.dates.size,dailyRate=Number(e?.dailyRate)||0;return{employeeId:e?.employeeId||row.employeeId,name:e?.name||"Unregistered employee",position:e?.position||"",registered:!!e,active:e?.active!==false,attendanceSource:e?.attendanceSource||"TASKS",taskCount:row.taskCount,paidDays,dailyRate,grossPay:paidDays*dailyRate};}).sort((a,b)=>a.employeeId.localeCompare(b.employeeId));}
function totals(){const grossPay=payrollRows.reduce((s,r)=>s+Number(r.grossPay||0),0),deductions=payrollRows.reduce((s,r)=>s+Number(r.deductions||0),0),additions=payrollRows.reduce((s,r)=>s+Number(r.additions||0),0);return{employeeCount:payrollRows.length,paidDays:payrollRows.reduce((s,r)=>s+r.paidDays,0),taskCount:payrollRows.reduce((s,r)=>s+r.taskCount,0),grossPay,additions,deductions,netPay:grossPay-deductions};}
function setRunStatus(status="UNSAVED"){if(!currentRun)status="UNSAVED";ui.runStatus.className=`run-status ${status}`;ui.runStatus.textContent=status==="UNSAVED"?"Unsaved payroll":`Payroll status: ${status}`;const has=payrollRows.length>0,editable=status==="UNSAVED"||status==="DRAFT";ui.saveDraftBtn.disabled=!has||!editable;ui.finalizeBtn.disabled=!has||!editable;ui.markPaidBtn.disabled=!has||status!=="FINALIZED";ui.exportBtn.disabled=!has;ui.printBtn.disabled=!has;}
function renderPayroll(){const term=ui.searchBox.value.trim().toLowerCase();const rows=payrollRows.filter(r=>`${r.employeeId} ${r.name} ${r.position}`.toLowerCase().includes(term));ui.payrollBody.innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.employeeId)}</strong></td><td>${esc(r.name)}</td><td>${esc(r.position||"—")}</td><td class="number">${r.taskCount}</td><td class="number">${r.paidDays}</td><td class="number">${money(r.dailyRate)}</td><td class="number gross">${money(r.grossPay)}</td><td class="${r.registered?"rate-saved":"rate-missing"}">${r.registered?(r.active?"Registered":"Inactive"):"Add employee"}</td></tr>`).join(""):'<tr><td colspan="8" class="empty">No matching payroll records.</td></tr>';const t=totals();ui.employeeCount.textContent=t.employeeCount;ui.workdayCount.textContent=t.paidDays;ui.taskCount.textContent=t.taskCount;ui.grossTotal.textContent=money(t.grossPay);ui.periodLabel.textContent=ui.dateFrom.value&&ui.dateTo.value?`${ui.dateFrom.value} to ${ui.dateTo.value} · One paid day per assigned date with completed work.`:"Generate a payroll period to see results.";setRunStatus(currentRun?.status);}
async function generatePayroll(){const from=ui.dateFrom.value,to=ui.dateTo.value;if(!from||!to)return message("Select both payroll dates.","error");if(from>to)return message("Starting date cannot be after ending date.","error");ui.loadBtn.disabled=true;message("Reading employees, tasks, attendance, and leave...");try{await loadEmployees();const existing=await getDoc(doc(db,"payrollRuns",runId()));if(existing.exists()&&["FINALIZED","PAID"].includes(existing.data().status)){currentRun={id:existing.id,...existing.data()};payrollRows=currentRun.rows||[];message(`Loaded the existing ${currentRun.status.toLowerCase()} payroll.`,"success");}else{const [tasks,manual]=await Promise.all([loadCompletedTasks(from,to),loadManualData(from,to)]);payrollRows=calculatePayroll(tasks,manual);currentRun={id:runId(),status:existing.exists()?"DRAFT":"UNSAVED"};const missing=payrollRows.filter(r=>!r.registered).length;message(payrollRows.length?`Payroll generated.${missing?` Add ${missing} missing employee record(s) before saving.`:" Review and save the draft."}`:"No paid work or leave found for this period.",missing?"error":"success");}renderPayroll();}catch(error){console.error(error);payrollRows=[];currentRun=null;renderPayroll();message(`Could not generate payroll: ${error.message||error}`,"error");}finally{ui.loadBtn.disabled=false;}}
function validateRun(){if(!payrollRows.length){message("There is no payroll to save.","error");return false;}const missing=payrollRows.filter(r=>!r.registered||r.dailyRate<=0);if(missing.length){message(`Add employee records and daily rates for: ${missing.map(r=>r.employeeId).join(", ")}.`,"error");return false;}return true;}
async function saveRun(status){if(!validateRun())return false;const rows=payrollRows.map(({key,dates,...r})=>calculatePhilippineDeductions(r));payrollRows=rows;const t=totals();const payload={periodFrom:ui.dateFrom.value,periodTo:ui.dateTo.value,payFrequency:"SEMI_MONTHLY",governmentDeductions:"ALL_EMPLOYEES",deductionTiming:"SPLIT_BETWEEN_CUTOFFS",preparedByRole:"HR",status,rows,totals:t,updatedAt:serverTimestamp(),...(status==="DRAFT"?{draftedAt:serverTimestamp()}:{finalizedAt:serverTimestamp()})};await setDoc(doc(db,"payrollRuns",runId()),payload,{merge:true});await addDoc(collection(db,"payrollAuditLogs"),{payrollRunId:runId(),action:status==="DRAFT"?"SAVE_DRAFT":"FINALIZE",role:"HR",createdAt:serverTimestamp()});currentRun={id:runId(),...payload,status};setRunStatus(status);return true;}
async function saveDraft(){try{if(await saveRun("DRAFT"))message("Payroll draft saved.","success");}catch(error){console.error(error);message(`Draft could not be saved: ${error.message||error}`,"error");}}
async function finalizeRun(){if(!confirm("Finalize this payroll? Employee amounts will be locked."))return;try{if(await saveRun("FINALIZED"))message("Payroll finalized.","success");}catch(error){console.error(error);message(`Payroll could not be finalized: ${error.message||error}`,"error");}}
async function markPaid(){if(!currentRun||currentRun.status!=="FINALIZED")return;if(!confirm("Mark this payroll as paid?"))return;try{await setDoc(doc(db,"payrollRuns",currentRun.id),{status:"PAID",paidAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,"payrollAuditLogs"),{payrollRunId:currentRun.id,action:"MARK_PAID",role:"HR",createdAt:serverTimestamp()});currentRun.status="PAID";setRunStatus("PAID");message("Payroll marked as paid.","success");}catch(error){console.error(error);message("Payroll could not be marked as paid.","error");}}

async function loadHistory(){ui.historyBody.innerHTML='<tr><td colspan="7" class="empty">Loading payroll history...</td></tr>';try{const snap=await getDocs(collection(db,"payrollRuns"));payrollHistory=[];snap.forEach(d=>payrollHistory.push({id:d.id,...d.data()}));payrollHistory.sort((a,b)=>String(b.periodTo).localeCompare(String(a.periodTo)));ui.historyBody.innerHTML=payrollHistory.length?payrollHistory.map(r=>`<tr><td><strong>${esc(r.periodFrom)}</strong> to <strong>${esc(r.periodTo)}</strong></td><td><span class="status-pill ${esc(r.status)}">${esc(r.status)}</span></td><td class="number">${r.totals?.employeeCount||0}</td><td class="number">${r.totals?.paidDays||0}</td><td class="number gross">${money(r.totals?.grossPay)}</td><td>${dateText(r.paidAt)}</td><td><button class="small-btn" data-view-run="${esc(r.id)}">View</button></td></tr>`).join(""):'<tr><td colspan="7" class="empty">No saved payroll periods.</td></tr>';}catch(error){console.error(error);ui.historyBody.innerHTML='<tr><td colspan="7" class="empty">Unable to load payroll history.</td></tr>';message("Unable to load payroll history.","error");}}
function viewRun(id){const run=payrollHistory.find(r=>r.id===id);if(!run)return;ui.dateFrom.value=run.periodFrom;ui.dateTo.value=run.periodTo;payrollRows=run.rows||[];currentRun=run;renderPayroll();showView("payrollView");message(`Loaded ${run.status.toLowerCase()} payroll ${run.periodFrom} to ${run.periodTo}.`,"success");}
function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`;}
function exportCsv(){const lines=[["Period From","Period To","Employee ID","Name","Position","Completed Tasks","Paid Days","Daily Rate","Gross Pay","Status"].map(csvCell).join(",")];payrollRows.forEach(r=>lines.push([ui.dateFrom.value,ui.dateTo.value,r.employeeId,r.name,r.position,r.taskCount,r.paidDays,Number(r.dailyRate).toFixed(2),Number(r.grossPay).toFixed(2),currentRun?.status||"UNSAVED"].map(csvCell).join(",")));const blob=new Blob(["\ufeff"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`payroll_${ui.dateFrom.value}_to_${ui.dateTo.value}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}

const today=todayPH();ui.dateFrom.value=`${today.slice(0,7)}-01`;ui.dateTo.value=today;
ui.employeeForm.addEventListener("submit",saveEmployee);ui.cancelEmployeeBtn.addEventListener("click",resetEmployeeForm);ui.employeeSearch.addEventListener("input",renderEmployees);ui.employeeBody.addEventListener("click",e=>{if(e.target.dataset.edit)editEmployee(e.target.dataset.edit);if(e.target.dataset.toggle)toggleEmployee(e.target.dataset.toggle);});ui.loadBtn.addEventListener("click",generatePayroll);ui.saveDraftBtn.addEventListener("click",saveDraft);ui.finalizeBtn.addEventListener("click",finalizeRun);ui.markPaidBtn.addEventListener("click",markPaid);ui.exportBtn.addEventListener("click",exportCsv);ui.printBtn.addEventListener("click",()=>window.print());ui.searchBox.addEventListener("input",renderPayroll);ui.refreshHistoryBtn.addEventListener("click",loadHistory);ui.historyBody.addEventListener("click",e=>{if(e.target.dataset.viewRun)viewRun(e.target.dataset.viewRun);});
loadEmployees();if(location.hash==="#employees")showView("employeesView");
